# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(467, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 0, 391, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.screen_id_1 = QtWidgets.QLineEdit(self.login)
        self.screen_id_1.setGeometry(QtCore.QRect(40, 30, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.screen_id_1.setFont(font)
        self.screen_id_1.setObjectName("screen_id_1")
        self.screen_password_1 = QtWidgets.QLineEdit(self.login)
        self.screen_password_1.setGeometry(QtCore.QRect(40, 100, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.screen_password_1.setFont(font)
        self.screen_password_1.setObjectName("screen_password_1")
        self.Button_log_in = QtWidgets.QPushButton(self.login)
        self.Button_log_in.setGeometry(QtCore.QRect(120, 180, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_log_in.setFont(font)
        self.Button_log_in.setObjectName("Button_log_in")
        self.tabWidget.addTab(self.login, "")
        self.sign_in = QtWidgets.QWidget()
        self.sign_in.setObjectName("sign_in")
        self.screen_id_2 = QtWidgets.QLineEdit(self.sign_in)
        self.screen_id_2.setGeometry(QtCore.QRect(30, 30, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.screen_id_2.setFont(font)
        self.screen_id_2.setObjectName("screen_id_2")
        self.screen_password_2 = QtWidgets.QLineEdit(self.sign_in)
        self.screen_password_2.setGeometry(QtCore.QRect(30, 90, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.screen_password_2.setFont(font)
        self.screen_password_2.setObjectName("screen_password_2")
        self.Button_sign_in = QtWidgets.QPushButton(self.sign_in)
        self.Button_sign_in.setGeometry(QtCore.QRect(120, 180, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_sign_in.setFont(font)
        self.Button_sign_in.setObjectName("Button_sign_in")
        self.tabWidget.addTab(self.sign_in, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 467, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_log_in.setText(_translate("MainWindow", "log in"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.login), _translate("MainWindow", "login"))
        self.Button_sign_in.setText(_translate("MainWindow", "sign in"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sign_in), _translate("MainWindow", "sign in"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
